# SUMO配置（集中到 green-traffic.sumo 下）
green-traffic:
  sumo:
    image: ${SUMO_IMAGE:ghcr.io/eclipse-sumo/sumo:v1_27_1}
    working-directory: ${SUMO_WORKING_DIRECTORY:/tmp/sumo}
    simulation:
      duration: 120
      step-length: 0.1
      grid-number: 2
      grid-length: 300
    traci:
      port: 8813
      enabled: true